  # Run pipeline whenever a commit or tag is pushed
  trigger:
    branches:
      include:
      - '*'
    tags:
      include: 
      - '*'

  variables:
    BuildConfiguration: release

  pool:
    vmImage: ubuntu-latest

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

#     Install the dependencies
#     Run the tests
#     Remove the tests before we package up for deployment      

  - task: Npm@1
    displayName: Install Application Dependencies
    
  #- script: |
  #    npm install
  #    npm run test
  #    rm -rf ./__tests__
  #  displayName: 'npm install and test'

 
  - task: AWSCLI@1
  # Run the following command: aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
    inputs:
      regionName: 'eu-west-1'
      awsCommand: 'cloudformation'
      awsSubCommand: 'package'
      awsArguments: '--template template.yml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1kni8z5nxcykx --output-template template-export.yml'


 - task: AWSCLI@1
  # Run the following command: aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
    inputs:
      regionName: 'eu-west-1'
      awsCommand: 'cloudformation'
      awsSubCommand: 'deploy'
      awsArguments: '--template-file template-export.yml --stack-name AzureDevopsAlbumStack --capabilities CAPABILITY_IAM'
