  # Run pipeline whenever a commit or tag is pushed
  trigger:
    branches:
      include:
      - '*'
    tags:
      include: 
      - '*'

  variables:
    BuildConfiguration: release

  pool:
    vmImage: ubuntu-latest

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
#      npm run build
    displayName: 'npm install and build'

 
  - task: AWSCLI@1
    inputs:
      regionName: 'eu-west-1'
      awsCommand: 's3'
      awsSubCommand: 'ls'
