AWSTemplateFormatVersion: 2010-09-09
Description: NickSAMAlbums
Transform:
- AWS::Serverless-2016-10-31
Globals:
  Function:
    Environment:
      Variables:
        TABLE_NAME: nick_albums
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 100
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"
Resources:
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-items.getAllItemsHandler
      Description: A simple example includes a HTTP get method to get all items from
        a DynamoDB table.
      Policies:
      - DynamoDBCrudPolicy:
          TableName: nick_albums
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-p7wqfpig28su/f61f039f4f54246dfa6181ea484af336
  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-by-id.getByIdHandler
      Description: A simple example includes a HTTP get method to get one item by
        id from a DynamoDB table.
      Policies:
      - DynamoDBCrudPolicy:
          TableName: nick_albums
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-p7wqfpig28su/f61f039f4f54246dfa6181ea484af336
  putItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-item.putItemHandler
      Description: A simple example includes a HTTP post method to add one item to
        a DynamoDB table.
      Policies:
      - DynamoDBCrudPolicy:
          TableName: nick_albums
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-p7wqfpig28su/f61f039f4f54246dfa6181ea484af336
Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
